"""
Django settings for afetos project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Railway'de (ve her production ortamında) SECRET_KEY ortam değişkeninden
# okunur — kod içine hardcode edilmiş anahtar YOKTUR. Yerelde .env veya
# shell'de SECRET_KEY tanımlanmazsa geliştirme için sabit bir varsayılan
# kullanılır (bu varsayılan production'da KULLANILMAMALI).
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-xjfxcmt$1=uu@_f9@eypy+bbjzm(23ghg7hvhkxluf)sx2b158',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Railway'in verdiği varsayılan *.up.railway.app adresi + ALLOWED_HOSTS
# ortam değişkeninden (virgülle ayrılmış) ek host eklenebilir.
ALLOWED_HOSTS = ['.up.railway.app']
_ekstra_hostlar = os.environ.get('ALLOWED_HOSTS', '')
if _ekstra_hostlar:
    ALLOWED_HOSTS += [h.strip() for h in _ekstra_hostlar.split(',') if h.strip()]

# Railway'in reverse proxy'si HTTPS'i sonlandırıp isteği HTTP olarak
# uygulamaya iletir; Django'nun bunu HTTPS olarak tanıması gerekir —
# aksi halde login/logout POST formlarında CSRF doğrulaması başarısız olur.
CSRF_TRUSTED_ORIGINS = ['https://*.up.railway.app']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'daphne',  # 'runserver' komutunu ASGI (WebSocket destekli) hale getirir; listenin en başında olmalı
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Üçüncü parti
    'channels',
    'rest_framework',
    # AFETOS app'leri
    'ihbarlar',
    'olaylar',
    'ekipler',
    'dashboard',
    'hesaplar',
    'deprem',
]

# Kandilli deprem proxy'si (deprem/views.py) için önbellek. Prototip
# kapsamında bellek-içi LocMemCache yeterli — Redis'e geçilmedi.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# --- Kimlik doğrulama ---
# Giriş yapmamış kullanıcı @login_required korumalı bir sayfaya gidince
# buraya yönlendirilir. Rol bazlı yönlendirme (koordinatör/saha/vatandaş)
# hesaplar/views.py içindeki rol_bazli_yonlendir() fonksiyonunda yapılır.
LOGIN_URL = 'login'

# Testler çok sayıda kullanıcı oluşturup giriş yapıyor; varsayılan PBKDF2
# hasher'ın yüksek iterasyon sayısı testleri gereksiz yavaşlatıyor. Sadece
# test çalıştırılırken (manage.py test) hızlı bir hasher kullan.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']

ASGI_APPLICATION = 'afetos.asgi.application'

# Canlı güncelleme (WebSocket) için kanal katmanı. Bu prototipte tek
# process/tek sunucu yeterli olduğu için bellek-içi (in-memory) katman
# kullanılıyor; Redis gibi harici bir bağımlılık eklenmedi.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # whitenoise: statik dosyaları ayrı bir web sunucusu (nginx vb.)
    # olmadan doğrudan Django/Daphne üzerinden verimli şekilde sunar —
    # Railway'de bunun dışında bir statik dosya sunucusu yok.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'afetos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.nav_sekmeleri',
            ],
        },
    },
]

WSGI_APPLICATION = 'afetos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Railway'de kalıcı bir Volume mount edilip DB_PATH ortam
        # değişkeni (ör. /data/db.sqlite3) o volume'a işaret edecek
        # şekilde ayarlanır — deploy'lar arası veri kaybolmasın diye.
        # Yerelde DB_PATH tanımsızsa proje kökündeki eski davranış korunur.
        'NAME': os.environ.get('DB_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# collectstatic bu dizine toplar (bkz. Procfile); whitenoise buradan sunar.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Kullanıcıların yüklediği dosyalar (ör. ihbar fotoğrafları)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# AFETOS — öncelik/güven skoru ayarları
# NOT: Bu katsayılar gerçek afet operasyonlarında kullanılacak kesin/onaylı
# değerler DEĞİLDİR. Sadece prototip/simülasyon amaçlıdır ve ileride
# scoring.py içindeki fonksiyonlarda kullanılmak üzere burada tutulur,
# böylece kod değiştirmeden kolayca ayarlanabilirler.
# ---------------------------------------------------------------------------

# Öncelik skoru bileşen ağırlıkları (toplamı 1.0 olacak şekilde tasarlanmalı)
ONCELIK_AGIRLIKLARI = {
    'kisi_etkisi': 0.25,
    'tibbi_aciliyet': 0.30,
    'olay_riski': 0.20,
    'ulasilabilirlik': 0.15,
    'zaman_faktoru': 0.10,
}

# Öncelik skoru bileşenlerinin doyma (saturation) eşikleri — bu değere
# ulaşan/geçen ihbar o bileşen için tam puanı (100) alır. Değerler prototip
# amaçlı seçilmiştir, gerçek afet istatistiklerine dayanmaz.
ONCELIK_KISI_ETKISI_DOYMA_ESIGI = 100       # bu sayıda etkilenen kişide bileşen 100 olur
ONCELIK_YARALI_DOYMA_ESIGI = 15             # bu sayıda yaralıda bileşen 100 olur
ONCELIK_ZAMAN_DOYMA_ESIGI_DAKIKA = 180      # bu kadar süre müdahalesiz kalınca bileşen 100 olur

# Olay türüne göre kabaca risk seviyesi (0-100). 'diger' için tanımsızsa
# ONCELIK_VARSAYILAN_OLAY_RISKI kullanılır.
OLAY_TURU_RISK_PUANLARI = {
    'deprem_hasari': 85,
    'yangin': 90,
    'tibbi': 75,
    'enkaz': 95,
    'diger': 40,
}
ONCELIK_VARSAYILAN_OLAY_RISKI = 40

# Ulaşılabilirlik puanı henüz bilinmiyorsa (ör. ekip mesafesi adım 5'te
# hesaplanmadan önce) kullanılacak nötr varsayılan.
ONCELIK_VARSAYILAN_ULASILABILIRLIK = 50

# İhbar kümeleme yarıçapı (metre) — bu mesafe içindeki ihbarlar aynı
# olay kümesine dahil edilir.
KUMELEME_YARICAPI_METRE = 400

# Güven skoru hesaplama katsayıları (bkz. olaylar/scoring.py)
# - GUVEN_BAGIMSIZ_IHBAR_KATSAYISI: 0-1 arası; küçüldükçe her yeni bağımsız
#   ihbar taban skoru daha hızlı yükseltir (diminishing-returns eğrisi).
# - GUVEN_TUTARLILIK_AGIRLIGI / GUVEN_CELISKI_CEZA_AGIRLIGI / GUVEN_FOTOGRAF_BONUSU:
#   puan cinsinden düzeltme ağırlıkları.
# - GUVEN_DOGRULAMA_ESIGI: bu skorun altındaki kümeler 'dogrulaniyor'
#   durumuna işaretlenir (ASLA silinmez).
GUVEN_BAGIMSIZ_IHBAR_KATSAYISI = 0.65
GUVEN_TUTARLILIK_AGIRLIGI = 12
GUVEN_CELISKI_CEZA_AGIRLIGI = 15
GUVEN_FOTOGRAF_BONUSU = 5
GUVEN_DOGRULAMA_ESIGI = 50

# Ekip önerisi — olay türüne göre hangi ekip türlerinin uygun olduğu
# (öncelik sırasıyla; listedeki ilk tür tercih edilir). Ekip modelinde
# sadece 'saglik', 'arama_kurtarma', 'lojistik' türleri var, bu yüzden
# örn. yangın için de en yakın karşılık arama_kurtarma olarak eşleştirildi.
# NOT: Bu eşleştirme kural tabanlı basit bir sözlüktür, prototip amaçlıdır.
EKIP_ONERISI_OLAY_TURU_ESLESTIRME = {
    'deprem_hasari': ['arama_kurtarma', 'lojistik'],
    'yangin': ['arama_kurtarma', 'lojistik'],
    'tibbi': ['saglik'],
    'enkaz': ['arama_kurtarma'],
    'diger': ['lojistik', 'arama_kurtarma', 'saglik'],
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
