# Generated by Django 6.1 on 2026-08-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ekip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150, verbose_name='Ekip Adı')),
                ('tur', models.CharField(choices=[('saglik', 'Sağlık'), ('arama_kurtarma', 'Arama Kurtarma'), ('lojistik', 'Lojistik')], max_length=20, verbose_name='Ekip Türü')),
                ('lat', models.FloatField(verbose_name='Enlem')),
                ('lng', models.FloatField(verbose_name='Boylam')),
                ('durum', models.CharField(choices=[('bosta', 'Boşta'), ('yolda', 'Yolda'), ('gorevde', 'Görevde')], default='bosta', max_length=20, verbose_name='Durum')),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ekip',
                'verbose_name_plural': 'Ekipler',
            },
        ),
    ]
