# Generated by Django 6.1 on 2026-08-13 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekipler', '0001_initial'),
        ('olaylar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekip',
            name='mevcut_olay_kumesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gorevli_ekipler', to='olaylar.olaykumesi', verbose_name='Mevcut Olay Kümesi'),
        ),
    ]
