# Generated by Django 6.1 on 2026-08-13 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekipler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlayKumesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkez_lat', models.FloatField(verbose_name='Merkez Enlem')),
                ('merkez_lng', models.FloatField(verbose_name='Merkez Boylam')),
                ('guven_skoru', models.PositiveSmallIntegerField(default=0, verbose_name='Güven Skoru')),
                ('oncelik_skoru', models.PositiveSmallIntegerField(default=0, verbose_name='Öncelik Skoru')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('dogrulaniyor', 'Doğrulanıyor'), ('mudahale_ediliyor', 'Müdahale Ediliyor'), ('tamamlandi', 'Tamamlandı')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_zamani', models.DateTimeField(auto_now=True)),
                ('atanan_ekip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atandigi_olay_kumeleri', to='ekipler.ekip', verbose_name='Atanan Ekip')),
            ],
            options={
                'verbose_name': 'Olay Kümesi',
                'verbose_name_plural': 'Olay Kümeleri',
                'ordering': ['-oncelik_skoru', '-olusturulma_zamani'],
            },
        ),
    ]
