# Generated by Django 6.1 on 2026-08-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekipler', '0003_ekip_user'),
        ('olaylar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestekTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('yonlendirildi', 'Yönlendirildi'), ('kapatildi', 'Kapatıldı')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('olay_kumesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destek_talepleri', to='olaylar.olaykumesi', verbose_name='Olay Kümesi')),
                ('talep_eden_ekip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destek_talepleri', to='ekipler.ekip', verbose_name='Talep Eden Ekip')),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'ordering': ['-olusturulma_zamani'],
            },
        ),
    ]
