# Generated by Django 6.1 on 2026-08-13 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olaylar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ihbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Enlem')),
                ('lng', models.FloatField(verbose_name='Boylam')),
                ('olay_turu', models.CharField(choices=[('deprem_hasari', 'Deprem Hasarı'), ('yangin', 'Yangın'), ('tibbi', 'Tıbbi'), ('enkaz', 'Enkaz'), ('diger', 'Diğer')], max_length=20, verbose_name='Olay Türü')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tahmini_kisi_sayisi', models.PositiveIntegerField(default=0, verbose_name='Tahmini Etkilenen Kişi Sayısı')),
                ('tahmini_yarali_sayisi', models.PositiveIntegerField(default=0, verbose_name='Tahmini Yaralı Sayısı')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='ihbar_fotograflari/', verbose_name='Fotoğraf')),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('olay_kumesi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ihbarlar', to='olaylar.olaykumesi', verbose_name='Olay Kümesi')),
            ],
            options={
                'verbose_name': 'İhbar',
                'verbose_name_plural': 'İhbarlar',
                'ordering': ['-olusturulma_zamani'],
            },
        ),
    ]
